apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  90: "default/demo:90"
  30101: "minecraft2/minecraft2:25565"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress-nginx
data:
  90: "default/demo:90"
  30101: "minecraft2/minecraft2:25565"
